NAME = libsmm
CFLAGS = -std=c99 -O3 -march=native
LIBS = $(shell gsl-config --cflags --libs)

all: ${NAME}.dylib test

test:   test.c smm.c smm.h
	gcc ${CFLAGS} test.c smm.c -o test ${LIBS}


${NAME}.dylib: smm.c smm.h
	gcc ${CFLAGS} -dynamiclib -o ${NAME}.so smm.c ${LIBS}


.PHONY: clean
clean:
	-rm ${NAME}.so smm.pyc
